### PR TITLE
Re-word some of the reporting & consequences sections

### PR DESCRIPTION
**Pull request by wildlyinaccurate**
The wording of these sections seems to be tailored more to public communities, and I'm not sure whether it's appropriate for internal business teams.

This is my attempt to make it more _business-y_ and relevant to our teams.

### CODE REVIEW

**Comment by wildlyinaccurate** [comment]
This is an improvement on what was there before, but it doesn't address the _who watches the watchers_ issue. What happens if the person's line manager doesn't agree that there is an issue, or if the reporter has the same line manager?

**Comment by wildlyinaccurate** [comment]
We think that the purpose of this Code of Conduct is to provide resolution steps that are simpler and less formal than the full-on BBC _Raise a Concern_ process. We need to define our own steps for dealing with reported issues.

**Comment by wildlyinaccurate** [comment]
Merging this now, with the caveat that it needs some work.

**Comment by samfrench** [comment]
I would say if someone has said something offensive be it on Slack, or in person then it should go through the formal BBC process. Often on Slack, sometimes it can be one persons point of view contradicting with another.

**Pull request merged**
